drop table if exists product cascade;
create table product(
    id bigint generated by default as identity,
    product_name varchar(255),
    price bigint,
    quantity bigint,
    primary key (id)
)